encoding: utf-8
permalink: /:title/
url: http://402332509.github.io
name: liujinghua.com
author: Harry
qq: 402332509
email: jinghualiu93@gmail.com
duoshuo: Harry
github: 402332509
douban: https://www.douban.com/people/67908937/


safe: true
paginate: 20
about: "这里是 刘敬华(Harry) 的个人博客，创建于 2015 年。用到了 Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
