markdown: rdiscount
permalink: /:title/
url: http://402332509.github.io
name: coaplus.cn
author: Harry
qq: 402332509
email: 402332509@qq.com
duoshuo: Harry
weibo: 402332509@qq.com
github: 402332509
pygments: true
safe: true
paginate: 20
about: "这里是 刘敬华(Harry) 的个人博客，创建于 2015 年。用到了 Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……<p><img src="album/personal/Koala.jpg" /></p>"
